language: r
sudo: required
dist: trusty

# Get mapshaper node module installed. Instructions from here:
# http://entulho.fiatjaf.alhur.es/guias/how-to-use-node-along-with-other-language-on-travis-ci/

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev libjq-dev
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mapshaper

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - udunits-bin
      - libudunits2-dev
env:
  - RGL_USE_NULL=TRUE
  
